apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: test-namespace
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
        - setWeight: 50
        - pause: {duration: 10s}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:non-existent-tag  # Introduce an error for testing
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
  progressDeadlineSeconds: 60  # Set a deadline for progress
  revisionHistoryLimit: 2      # Keep at least two revisions for rollback
  rollbackWindow:
    revisionLimit: 2            # Specifies the number of revisions to keep for rollback
  automatedRollout:
    failureCondition:
      - conditionType: "RolloutConditionProgressing"
        status: "False"
        reason: "ProgressDeadlineExceeded"
